"""
utils.py
Shared utility functions: session state helpers, data validation,
export utilities, and UI helper functions.
"""

import re
import json
import datetime
from typing import Dict, Any, Optional


def initialize_session_state(st) -> None:
    """Initialize all required Streamlit session state variables."""
    defaults = {
        "patient_data": {},
        "seizure_types": [{}],  # start with one empty seizure type
        "uploaded_docs": [],
        "generated_report": None,
        "report_error": None,
        "api_key": "",
    }
    for key, val in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = val


def validate_patient_data(data: Dict) -> list:
    """
    Basic validation of patient data.
    Returns a list of warning strings (empty if no warnings).
    """
    warnings = []

    age = data.get("current_age")
    onset = data.get("onset_age")
    if age and onset:
        if onset > age:
            warnings.append("Age at onset cannot be greater than current age.")
        if onset < 0 or age < 0:
            warnings.append("Ages must be non-negative.")

    if not data.get("seizure_types"):
        warnings.append("At least one seizure type description is recommended.")

    return warnings


def sanitize_text(text: Optional[str]) -> str:
    """Strip dangerous characters from free text fields."""
    if not text:
        return ""
    # Remove control characters
    text = re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]', '', text)
    return text.strip()


def export_report_as_markdown(report: str, patient_data: Dict) -> str:
    """
    Add header metadata to the report for export.
    """
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    age = patient_data.get("current_age", "?")
    sex = patient_data.get("sex", "?")
    header = (
        f"# Epilepsy Classification and Localization Report\n\n"
        f"**Generated:** {now}  \n"
        f"**Tool:** EpiloClassify v1.0 (Clinical Decision-Support)  \n"
        f"**Patient summary:** Age {age}, {sex}  \n\n"
        f"---\n\n"
        f"> ⚠️ **DISCLAIMER:** This report is generated by an AI-assisted clinical "
        f"decision-support tool for educational and research purposes only. "
        f"It does not constitute a medical diagnosis and must not replace the "
        f"judgment of a qualified epileptologist or neurologist.\n\n"
        f"---\n\n"
    )
    return header + report


def collect_seizure_type_data(sz_dict: Dict) -> Dict:
    """Sanitize and return a clean seizure type data dict."""
    return {
        "seizure_description": sanitize_text(sz_dict.get("seizure_description")),
        "aura": sz_dict.get("aura", False),
        "aura_description": sanitize_text(sz_dict.get("aura_description")),
        "awareness": sz_dict.get("awareness", "Unknown"),
        "motor_features": sanitize_text(sz_dict.get("motor_features")),
        "nonmotor_features": sanitize_text(sz_dict.get("nonmotor_features")),
        "automatisms": sz_dict.get("automatisms", False),
        "behavioral_arrest": sz_dict.get("behavioral_arrest", False),
        "speech_arrest": sz_dict.get("speech_arrest", False),
        "head_version": sz_dict.get("head_version", False),
        "eye_deviation": sz_dict.get("eye_deviation", False),
        "unilateral_tonic": sz_dict.get("unilateral_tonic", False),
        "clonic_movements": sz_dict.get("clonic_movements", False),
        "hypermotor_features": sz_dict.get("hypermotor_features", False),
        "sensory_symptoms": sanitize_text(sz_dict.get("sensory_symptoms")),
        "autonomic_symptoms": sanitize_text(sz_dict.get("autonomic_symptoms")),
        "emotional_symptoms": sanitize_text(sz_dict.get("emotional_symptoms")),
        "cognitive_symptoms": sanitize_text(sz_dict.get("cognitive_symptoms")),
        "postictal_confusion": sz_dict.get("postictal_confusion", False),
        "postictal_aphasia": sz_dict.get("postictal_aphasia", False),
        "todds_paresis": sz_dict.get("todds_paresis", False),
        "nocturnal": sz_dict.get("nocturnal", False),
        "duration": sanitize_text(sz_dict.get("duration")),
        "clustering": sz_dict.get("clustering", False),
        "triggered": sz_dict.get("triggered", False),
        "trigger_description": sanitize_text(sz_dict.get("trigger_description")),
        "expert_summary": sanitize_text(sz_dict.get("expert_summary")),
    }


def format_risk_factors_display(rf: Dict) -> str:
    """Format risk factors dict for readable display."""
    labels = {
        "perinatal_insult": "Perinatal insult",
        "febrile_seizures": "Febrile seizures",
        "cns_infection": "CNS infection",
        "head_trauma": "Head trauma",
        "stroke": "Stroke",
        "brain_tumor": "Brain tumor",
        "developmental_delay": "Developmental delay",
        "family_history": "Family history of epilepsy",
        "known_genetic_syndrome": "Known genetic syndrome",
        "prior_neurosurgery": "Prior neurosurgery",
    }
    active = [labels[k] for k in labels if rf.get(k)]
    if rf.get("other_text"):
        active.append(f"Other: {rf['other_text']}")
    return ", ".join(active) if active else "None"
